**Numpy(Numerical Python)** - это библиотека для языка программирования Python, которая предоставляет высокопроизводительные возможности для работы

**ndarray** - это быстрый и гибкий контейнер для хранения больших наборов данных в Python

* ndarray.ndim - число осей (измерений) массива
* ndarray.shape - размеры массива, его форма. Число элементов кортежа shape равно рангу массива то есть nd.
* ndarray.size - число всех элементов массива
* inarray.type - объект, описывающий тип элементов массива
`bool_`
`character`,
`int_, int8, int16, int32, int64`,
`float_, float8, float16, float32, float64`,
`complex_, complex64`
`object`_
* ndarray.itemsize - размер каждого элемента массива в байтах
* darray.data - буфер с фактическими элементами массива

In [7]:
import numpy as np

In [8]:
#создание массива
datal = [ [5.2, 3.0, 4.5] , [9.1, 0.1, 0.3]]
arrl = np.array(datal) 
arrl

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [9]:
arrl.ndim 

2

In [10]:
arrl.size

6

In [11]:
arrl.shape

(2, 3)

In [12]:
arrl.dtype

dtype('float64')

In [13]:
arrl.itemsize

8

In [14]:
np.zeros(10) #создает массив, состоящий из n количества 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones((2,2)) #создает массив, состоящий из n количества 1

array([[1., 1.],
       [1., 1.]])

In [16]:
np.arange(15) #создает массив, отитерированный от нулевого элемента до n, его не включая

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.linspace(0, 1, 25)  #создает массив, от 0 до 1, включив указанное количество (25) аргументов


array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [18]:
#единичная матрица
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Операции между массивами и скалярами

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [20]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [21]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### Случайные массивы

In [23]:
np.random.randn(3,2)

array([[ 1.59934326, -0.21222357],
       [ 0.01741958,  0.37952563],
       [-0.48938847, -1.5655865 ]])

In [24]:
np.random.randint(0, 1000, 4)  #создает случайный массив, от 0 до 1000, включив в него всего 4 элемента


array([982, 536, 273, 190])

### Индексирование

Схоже с индексированием списков.

In [25]:
np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [26]:
#многомерные массивы
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [27]:
arr2d[0, 2] 

3

In [22]:
arr2d[0][2]

3

In [29]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
arr3d[1,1][2]

12

In [30]:
arr3d.shape

(2, 2, 3)

In [24]:
arr3d[:1,:1,1:] #начиная с единицы по трем осям выбрали необходимый для нас элемент

array([[[2, 3]]])

In [32]:
#булевое индексирование
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [33]:
mask = (names == 'Bob') | (names == 'Will') 
mask

array([ True, False,  True,  True,  True, False, False])

In [34]:
names[mask]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

### Транспонирование массивов

In [35]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d.shape

(2, 2, 3)

In [37]:
arr3d.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [38]:
arr3d.T.shape

(3, 2, 2)

### Поэлементные операции над массивами

Это векторные обертки вокруг простых функций, которые принимают одно или несколько скалярных значений и порождают один или несколько скалярных результатов.

In [39]:
np.sqrt(arr3d)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [40]:
np.exp(arr3d)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

### Математические и статистические операции

In [41]:
arr = np.random.randn(5, 4) 
arr

array([[ 0.84993293, -0.97830661, -0.87653838, -0.32926317],
       [ 0.48595049,  0.50320929, -0.21413282, -1.40913339],
       [ 0.66736473,  0.25555894, -0.00787442,  1.40883715],
       [-0.55673962,  0.28548107, -0.84472809, -0.78792466],
       [ 0.06954687, -0.37944194,  1.45426928, -0.79303091]])

In [42]:
arr.shape

(5, 4)

In [43]:
arr.mean()

-0.05984816310704764

In [44]:
arr.sum()

-1.1969632621409527

In [45]:
np.max(arr)

1.454269278831511

In [39]:
arr.sum(axis = 0) #по оси 0, то есть по строкам

array([-0.79301447, -4.117937  , -1.0865522 , -3.6220423 ])

In [46]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr.cumsum(axis = 0) #куммулятивная сумма

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [47]:
arr.cumprod(axis = 0) #куммулятивное произведение

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

### Сортировка

In [53]:
arr = np.random.randn(8) 
arr

array([-0.55702851, -0.39430781, -0.06642921, -0.9604984 , -0.30207515,
       -1.00791303,  0.21719194, -1.21918146])

In [54]:
arr.sort()
arr

array([-1.21918146, -1.00791303, -0.9604984 , -0.55702851, -0.39430781,
       -0.30207515, -0.06642921,  0.21719194])

In [66]:
arr = np.random.randn(5,3) 
arr

array([[-1.90910807, -1.20955027,  1.08924707],
       [ 0.78818684, -0.6876422 ,  1.56716278],
       [-0.34720952,  0.07858776,  0.47460479],
       [-0.65121718, -0.58978152,  1.8351187 ],
       [-0.01562863,  0.98640082, -1.07019981]])

In [67]:
arr.sort(0) #сортировка с учетом строк
arr

array([[-1.90910807, -1.20955027, -1.07019981],
       [-0.65121718, -0.6876422 ,  0.47460479],
       [-0.34720952, -0.58978152,  1.08924707],
       [-0.01562863,  0.07858776,  1.56716278],
       [ 0.78818684,  0.98640082,  1.8351187 ]])

In [68]:
arr.sort(1) #сортировка с учетом столбцов
arr

array([[-1.90910807, -1.20955027, -1.07019981],
       [-0.6876422 , -0.65121718,  0.47460479],
       [-0.58978152, -0.34720952,  1.08924707],
       [-0.01562863,  0.07858776,  1.56716278],
       [ 0.78818684,  0.98640082,  1.8351187 ]])

In [48]:
#возвращает копию
arr = np.random.randn(5,3) 
np.sort(arr)

array([[-2.18155234, -0.60561026,  0.58686431],
       [-1.37264772, -0.14011607,  1.09171741],
       [-0.55673431, -0.3052277 ,  0.40597668],
       [-1.95869758, -1.52114351,  0.35866463],
       [-1.0612078 , -0.29071306,  1.8410877 ]])

In [49]:
arr = np.sort(arr)
arr

array([[-2.18155234, -0.60561026,  0.58686431],
       [-1.37264772, -0.14011607,  1.09171741],
       [-0.55673431, -0.3052277 ,  0.40597668],
       [-1.95869758, -1.52114351,  0.35866463],
       [-1.0612078 , -0.29071306,  1.8410877 ]])

### Хранение массивов на диске в двоичном формате 

*np.save* и *np.load* - основные функции для эффективного сохранения и загрузки данных с диска. По умолчанию массивы хранятся в несжатом двоичном формате в файле с расширением *.npy*. 

In [57]:
arr = np.arange(10)

In [58]:
np.save('some_array', arr) 

In [60]:
np.load( 'some_array.npy') 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Можно сохранить несколько массивов в ziр-архиве с помощью функции np. savez, которой массивы передаются в виде именованных аргументов: 

In [61]:
np.savez('array_archive.npz', a=arr, b=arr) 

In [62]:
arch = np.load('array_archive.npz') 

In [63]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])